version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 5000:5000
      - 80:80
      - 443:443
    volumes:
      - ./configuration/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./configuration/nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./configuration/nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key
      - ./configuration/nginx/html:/usr/share/nginx/html
    depends_on:
      - api
    restart: always
    networks:
      - iot-network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: plant172839
      MYSQL_USER: polipharm
      MYSQL_PASSWORD: plant172839
      TZ: "Asia/Bangkok" # ตั้งค่าโซนเวลาเป็น Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - ./configuration/database:/var/lib/mysql
    restart: always
    networks:
      - iot-network
  
  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1884:1883"
    volumes:
      - ./configuration/mosquitto/config/:/mosquitto/config/
    depends_on:
      - db
    networks:
      - iot-network
      
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DEV_MODE: "true"
      MQTT_CONTAINER_NAME: server-api-1
    env_file:
      - .env # ✅ โหลดค่าจาก .env
    volumes:
      - ./configuration/nginx/html/assets/images/machine:/usr/src/app/images
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: always
    networks:
      - iot-network

volumes:
  db_data:

networks:
  iot-network:
    name: iot-network
    driver: bridge
