// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Printer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_LoadingPage
void ui_LoadingPage_screen_init(void);
lv_obj_t * ui_LoadingPage;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Copyright1;
lv_obj_t * ui_LoadingLabel;
// CUSTOM VARIABLES

// SCREEN: ui_DetailsPage
void ui_DetailsPage_screen_init(void);
lv_obj_t * ui_DetailsPage;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Copyright2;
lv_obj_t * ui_SerialNumber;
lv_obj_t * ui_MachineName;
lv_obj_t * ui_UpdateDetails;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Image10;
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Image11;
void ui_event_QrCode(lv_event_t * e);
lv_obj_t * ui_QrCode;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

// SCREEN: ui_QrCodePage
void ui_QrCodePage_screen_init(void);
lv_obj_t * ui_QrCodePage;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_QrCodeImg;
void ui_event_Details2(lv_event_t * e);
lv_obj_t * ui_Details2;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Image16;
lv_obj_t * ui_SerialNumber2;
// CUSTOM VARIABLES

// SCREEN: ui_LoginPage
void ui_LoginPage_screen_init(void);
lv_obj_t * ui_LoginPage;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label12;
lv_obj_t * ui_PnEmployeeID1;
lv_obj_t * ui_EmployeeIDValue1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_PnEmployeeID2;
lv_obj_t * ui_EmployeeIDValue2;
lv_obj_t * ui_Copyright3;
lv_obj_t * ui_Login;
lv_obj_t * ui_Label30;
void ui_event_Details(lv_event_t * e);
lv_obj_t * ui_Details;
lv_obj_t * ui_Image8;
void ui_event_UserGuide(lv_event_t * e);
lv_obj_t * ui_UserGuide;
lv_obj_t * ui_Image9;
lv_obj_t * ui_PnLoginKeyboard;
lv_obj_t * ui_LoginKeyboard;
lv_obj_t * ui_LoginInput;
// CUSTOM VARIABLES

// SCREEN: ui_UserGuidePage
void ui_UserGuidePage_screen_init(void);
lv_obj_t * ui_UserGuidePage;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Image13;
void ui_event_Details1(lv_event_t * e);
lv_obj_t * ui_Details1;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
lv_obj_t * ui_MainPage;
lv_obj_t * ui_Header;
lv_obj_t * ui_Logout;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Date;
lv_obj_t * ui_Time;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_EmployeeID1;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_EmployeeID2;
lv_obj_t * ui_Mode;
lv_obj_t * ui_Label8;
lv_obj_t * ui_ModeLabel;
lv_obj_t * ui_SettingMode;
lv_obj_t * ui_Image1;
lv_obj_t * ui_LowBattery;
lv_obj_t * ui_GramPanel;
lv_obj_t * ui_Copyright4;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_CurrentWeight;
lv_obj_t * ui_GramUnit;
lv_obj_t * ui_Label16;
lv_obj_t * ui_OkGramCount;
lv_obj_t * ui_Label17;
lv_obj_t * ui_NgGramCount;
lv_obj_t * ui_ResetGramCount;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Image4;
lv_obj_t * ui_SetMinWeight;
lv_obj_t * ui_MinWeight;
lv_obj_t * ui_Label10;
lv_obj_t * ui_SetMaxWeight;
lv_obj_t * ui_MaxWeight;
lv_obj_t * ui_Label7;
lv_obj_t * ui_LedGramResult;
lv_obj_t * ui_GramResult;
lv_obj_t * ui_PrintLogo;
lv_obj_t * ui_PcsPanel;
lv_obj_t * ui_Copyright5;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_CurrentPcs;
lv_obj_t * ui_PcsUnit;
lv_obj_t * ui_OkPcsCount;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_NgPcsCount;
lv_obj_t * ui_ResetPcsCount;
lv_obj_t * ui_Label19;
lv_obj_t * ui_LedPcsResult;
lv_obj_t * ui_PcsResult;
lv_obj_t * ui_SetPcs;
lv_obj_t * ui_PcsMonitor;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_PrintPcs;
lv_obj_t * ui_Label14;
lv_obj_t * ui_SettingPanel;
lv_obj_t * ui_TabSettings;
lv_obj_t * ui_TabTestBalancePage;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_TestBalanceValue;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label35;
lv_obj_t * ui_TestAlarm2;
lv_obj_t * ui_Label42;
lv_obj_t * ui_TestAlarm1;
lv_obj_t * ui_Label43;
lv_obj_t * ui_TabTestPrinterPage;
lv_obj_t * ui_TestPrinterPanel;
lv_obj_t * ui_TestPrinterInput;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Label40;
lv_obj_t * ui_PrintTest;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Image19;
lv_obj_t * ui_TabWiFiSettingPage;
lv_obj_t * ui_SetWiFiNtpServer;
lv_obj_t * ui_WiFiNtpServer;
lv_obj_t * ui_SetWiFiServerIP;
lv_obj_t * ui_WiFiServerIP;
lv_obj_t * ui_SetWiFiPassWord;
lv_obj_t * ui_WiFiPassWord;
lv_obj_t * ui_SetWiFiSSID;
lv_obj_t * ui_WiFiSSID;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label26;
void ui_event_SaveWiFiSetting(lv_event_t * e);
lv_obj_t * ui_SaveWiFiSetting;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Image20;
void ui_event_FactoryReset(lv_event_t * e);
lv_obj_t * ui_FactoryReset;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Image21;
lv_obj_t * ui_ConfirmWiFiSettingsPanel;
lv_obj_t * ui_Image26;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Copyright7;
lv_obj_t * ui_ConfirmWiFiSettings;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Image25;
void ui_event_CacelWiFiSettings(lv_event_t * e);
lv_obj_t * ui_CacelWiFiSettings;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Image27;
lv_obj_t * ui_ConfirmFactoryResetPanel;
lv_obj_t * ui_Copyright6;
lv_obj_t * ui_Label46;
lv_obj_t * ui_ConfirmFactoryReset;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Image22;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Label49;
lv_obj_t * ui_Label13;
void ui_event_CacelFactoryReset(lv_event_t * e);
lv_obj_t * ui_CacelFactoryReset;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Label2;
lv_obj_t * ui_PNKEYBOARD;
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_input;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LoginPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_LoginPage_screen_init);
    }
}

void ui_event_QrCode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_QrCodePage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_QrCodePage_screen_init);
    }
}

void ui_event_Details2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DetailsPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DetailsPage_screen_init);
    }
}

void ui_event_Details(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DetailsPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DetailsPage_screen_init);
    }
}

void ui_event_UserGuide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_UserGuidePage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_UserGuidePage_screen_init);
    }
}

void ui_event_Details1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LoginPage, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_LoginPage_screen_init);
    }
}

void ui_event_SaveWiFiSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ConfirmWiFiSettingsPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_FactoryReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ConfirmFactoryResetPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_CacelWiFiSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ConfirmWiFiSettingsPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_CacelFactoryReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ConfirmFactoryResetPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_LoadingPage_screen_init();
    ui_DetailsPage_screen_init();
    ui_QrCodePage_screen_init();
    ui_LoginPage_screen_init();
    ui_UserGuidePage_screen_init();
    ui_MainPage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_LoadingPage);
}
