// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Printer

#ifndef _PRINTER_UI_H
#define _PRINTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_LoadingPage
void ui_LoadingPage_screen_init(void);
extern lv_obj_t * ui_LoadingPage;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Copyright1;
extern lv_obj_t * ui_LoadingLabel;
// CUSTOM VARIABLES

// SCREEN: ui_DetailsPage
void ui_DetailsPage_screen_init(void);
extern lv_obj_t * ui_DetailsPage;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Copyright2;
extern lv_obj_t * ui_SerialNumber;
extern lv_obj_t * ui_MachineName;
extern lv_obj_t * ui_UpdateDetails;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image10;
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image11;
void ui_event_QrCode(lv_event_t * e);
extern lv_obj_t * ui_QrCode;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

// SCREEN: ui_QrCodePage
void ui_QrCodePage_screen_init(void);
extern lv_obj_t * ui_QrCodePage;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_QrCodeImg;
void ui_event_Details2(lv_event_t * e);
extern lv_obj_t * ui_Details2;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_SerialNumber2;
// CUSTOM VARIABLES

// SCREEN: ui_LoginPage
void ui_LoginPage_screen_init(void);
extern lv_obj_t * ui_LoginPage;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_PnEmployeeID1;
extern lv_obj_t * ui_EmployeeIDValue1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_PnEmployeeID2;
extern lv_obj_t * ui_EmployeeIDValue2;
extern lv_obj_t * ui_Copyright3;
extern lv_obj_t * ui_Login;
extern lv_obj_t * ui_Label30;
void ui_event_Details(lv_event_t * e);
extern lv_obj_t * ui_Details;
extern lv_obj_t * ui_Image8;
void ui_event_UserGuide(lv_event_t * e);
extern lv_obj_t * ui_UserGuide;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_PnLoginKeyboard;
extern lv_obj_t * ui_LoginKeyboard;
extern lv_obj_t * ui_LoginInput;
// CUSTOM VARIABLES

// SCREEN: ui_UserGuidePage
void ui_UserGuidePage_screen_init(void);
extern lv_obj_t * ui_UserGuidePage;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image13;
void ui_event_Details1(lv_event_t * e);
extern lv_obj_t * ui_Details1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

// SCREEN: ui_MainPage
void ui_MainPage_screen_init(void);
extern lv_obj_t * ui_MainPage;
extern lv_obj_t * ui_Header;
extern lv_obj_t * ui_Logout;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_EmployeeID1;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_EmployeeID2;
extern lv_obj_t * ui_Mode;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_ModeLabel;
extern lv_obj_t * ui_SettingMode;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_LowBattery;
extern lv_obj_t * ui_GramPanel;
extern lv_obj_t * ui_Copyright4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_CurrentWeight;
extern lv_obj_t * ui_GramUnit;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_OkGramCount;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_NgGramCount;
extern lv_obj_t * ui_ResetGramCount;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_SetMinWeight;
extern lv_obj_t * ui_MinWeight;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_SetMaxWeight;
extern lv_obj_t * ui_MaxWeight;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_LedGramResult;
extern lv_obj_t * ui_GramResult;
extern lv_obj_t * ui_PrintLogo;
extern lv_obj_t * ui_PcsPanel;
extern lv_obj_t * ui_Copyright5;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_CurrentPcs;
extern lv_obj_t * ui_PcsUnit;
extern lv_obj_t * ui_OkPcsCount;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_NgPcsCount;
extern lv_obj_t * ui_ResetPcsCount;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_LedPcsResult;
extern lv_obj_t * ui_PcsResult;
extern lv_obj_t * ui_SetPcs;
extern lv_obj_t * ui_PcsMonitor;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_PrintPcs;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_SettingPanel;
extern lv_obj_t * ui_TabSettings;
extern lv_obj_t * ui_TabTestBalancePage;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_TestBalanceValue;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_TestAlarm2;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_TestAlarm1;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_TabTestPrinterPage;
extern lv_obj_t * ui_TestPrinterPanel;
extern lv_obj_t * ui_TestPrinterInput;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_PrintTest;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_TabWiFiSettingPage;
extern lv_obj_t * ui_SetWiFiNtpServer;
extern lv_obj_t * ui_WiFiNtpServer;
extern lv_obj_t * ui_SetWiFiServerIP;
extern lv_obj_t * ui_WiFiServerIP;
extern lv_obj_t * ui_SetWiFiPassWord;
extern lv_obj_t * ui_WiFiPassWord;
extern lv_obj_t * ui_SetWiFiSSID;
extern lv_obj_t * ui_WiFiSSID;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label26;
void ui_event_SaveWiFiSetting(lv_event_t * e);
extern lv_obj_t * ui_SaveWiFiSetting;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Image20;
void ui_event_FactoryReset(lv_event_t * e);
extern lv_obj_t * ui_FactoryReset;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_ConfirmWiFiSettingsPanel;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Copyright7;
extern lv_obj_t * ui_ConfirmWiFiSettings;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image25;
void ui_event_CacelWiFiSettings(lv_event_t * e);
extern lv_obj_t * ui_CacelWiFiSettings;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_ConfirmFactoryResetPanel;
extern lv_obj_t * ui_Copyright6;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_ConfirmFactoryReset;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label13;
void ui_event_CacelFactoryReset(lv_event_t * e);
extern lv_obj_t * ui_CacelFactoryReset;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_PNKEYBOARD;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_input;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_polipharm_png);    // assets/polipharm.png
LV_IMG_DECLARE(ui_img_update_png);    // assets/update.png
LV_IMG_DECLARE(ui_img_login_png);    // assets/login.png
LV_IMG_DECLARE(ui_img_1534850174);    // assets/qr-code.png
LV_IMG_DECLARE(ui_img_close_png);    // assets/close.png
LV_IMG_DECLARE(ui_img_house_png);    // assets/house.png
LV_IMG_DECLARE(ui_img_1661776595);    // assets/user-guide.png
LV_IMG_DECLARE(ui_img_count_png);    // assets/count.png
LV_IMG_DECLARE(ui_img_prt_png);    // assets/prt.png
LV_IMG_DECLARE(ui_img_hand_png);    // assets/hand.png
LV_IMG_DECLARE(ui_img_logout5_png);    // assets/logout5.png
LV_IMG_DECLARE(ui_img_energy_png);    // assets/energy.png
LV_IMG_DECLARE(ui_img_scale_png);    // assets/scale.png
LV_IMG_DECLARE(ui_img_printer_png);    // assets/printer.png
LV_IMG_DECLARE(ui_img_119302961);    // assets/data-storage.png
LV_IMG_DECLARE(ui_img_reset_png);    // assets/reset.png
LV_IMG_DECLARE(ui_img_1757177593);    // assets/wifi-signal.png
LV_IMG_DECLARE(ui_img_warning_png);    // assets/warning.png

// FONTS
LV_FONT_DECLARE(ui_font_Chakra130);
LV_FONT_DECLARE(ui_font_Chakra50);
LV_FONT_DECLARE(ui_font_Kanit50);
LV_FONT_DECLARE(ui_font_NotoSans100);
LV_FONT_DECLARE(ui_font_NotoSans60);
LV_FONT_DECLARE(ui_font_sukhumvit25);
LV_FONT_DECLARE(ui_font_sukhumvit30);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
