// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Printer

#include "../ui.h"

void ui_DetailsPage_screen_init(void)
{
    ui_DetailsPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DetailsPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DetailsPage, lv_color_hex(0x53E1FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DetailsPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_DetailsPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_DetailsPage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_DetailsPage);
    lv_img_set_src(ui_Image7, &ui_img_polipharm_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 267
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 267
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, -115);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 200);

    ui_Copyright2 = lv_label_create(ui_DetailsPage);
    lv_obj_set_width(ui_Copyright2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Copyright2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Copyright2, 0);
    lv_obj_set_y(ui_Copyright2, 222);
    lv_obj_set_align(ui_Copyright2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Copyright2, "CREATE BY NATTAPON PONDONKO");
    lv_obj_set_style_text_color(ui_Copyright2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Copyright2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Copyright2, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SerialNumber = lv_label_create(ui_DetailsPage);
    lv_obj_set_width(ui_SerialNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SerialNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SerialNumber, 0);
    lv_obj_set_y(ui_SerialNumber, 191);
    lv_obj_set_align(ui_SerialNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SerialNumber, "Serial number: ESP32-XXXXXXXX");
    lv_obj_set_style_text_color(ui_SerialNumber, lv_color_hex(0xF4660A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SerialNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SerialNumber, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MachineName = lv_label_create(ui_DetailsPage);
    lv_obj_set_width(ui_MachineName, 756);
    lv_obj_set_height(ui_MachineName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MachineName, 1);
    lv_obj_set_y(ui_MachineName, 55);
    lv_obj_set_align(ui_MachineName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MachineName, "XXXXXXX");
    lv_obj_set_style_text_color(ui_MachineName, lv_color_hex(0x695C62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MachineName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MachineName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MachineName, &ui_font_NotoSans100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdateDetails = lv_btn_create(ui_DetailsPage);
    lv_obj_set_width(ui_UpdateDetails, 175);
    lv_obj_set_height(ui_UpdateDetails, 55);
    lv_obj_set_x(ui_UpdateDetails, 0);
    lv_obj_set_y(ui_UpdateDetails, 140);
    lv_obj_set_align(ui_UpdateDetails, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpdateDetails, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UpdateDetails, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_UpdateDetails);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 23);
    lv_obj_set_y(ui_Label23, 0);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "อัพเดท");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_UpdateDetails);
    lv_img_set_src(ui_Image10, &ui_img_update_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -43);
    lv_obj_set_y(ui_Image10, 0);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 100);

    ui_Home = lv_btn_create(ui_DetailsPage);
    lv_obj_set_width(ui_Home, 177);
    lv_obj_set_height(ui_Home, 55);
    lv_obj_set_x(ui_Home, -185);
    lv_obj_set_y(ui_Home, 140);
    lv_obj_set_align(ui_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 23);
    lv_obj_set_y(ui_Label24, 0);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "LOGIN");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_Home);
    lv_img_set_src(ui_Image11, &ui_img_login_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, -52);
    lv_obj_set_y(ui_Image11, -3);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 180);

    ui_QrCode = lv_btn_create(ui_DetailsPage);
    lv_obj_set_width(ui_QrCode, 175);
    lv_obj_set_height(ui_QrCode, 55);
    lv_obj_set_x(ui_QrCode, 185);
    lv_obj_set_y(ui_QrCode, 140);
    lv_obj_set_align(ui_QrCode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QrCode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_QrCode, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_QrCode);
    lv_img_set_src(ui_Image12, &ui_img_1534850174);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, -57);
    lv_obj_set_y(ui_Image12, 0);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image12, 180);

    ui_Label29 = lv_label_create(ui_QrCode);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 22);
    lv_obj_set_y(ui_Label29, 2);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "QR CODE");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_QrCode, ui_event_QrCode, LV_EVENT_ALL, NULL);

}
