// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Printer

#include "../ui.h"

void ui_LoginPage_screen_init(void)
{
    ui_LoginPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoginPage, lv_color_hex(0x53E1FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LoginPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LoginPage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_LoginPage);
    lv_img_set_src(ui_Image2, &ui_img_polipharm_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 267
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 267
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -155);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 150);

    ui_Label12 = lv_label_create(ui_LoginPage);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -53);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "ป้อนรหัสคนเลือกแผงยา");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnEmployeeID1 = lv_obj_create(ui_LoginPage);
    lv_obj_set_width(ui_PnEmployeeID1, 332);
    lv_obj_set_height(ui_PnEmployeeID1, 59);
    lv_obj_set_x(ui_PnEmployeeID1, 0);
    lv_obj_set_y(ui_PnEmployeeID1, -7);
    lv_obj_set_align(ui_PnEmployeeID1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnEmployeeID1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EmployeeIDValue1 = lv_label_create(ui_PnEmployeeID1);
    lv_obj_set_width(ui_EmployeeIDValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmployeeIDValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EmployeeIDValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmployeeIDValue1, "XXXX");
    lv_obj_set_style_text_color(ui_EmployeeIDValue1, lv_color_hex(0xED2677), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EmployeeIDValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EmployeeIDValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EmployeeIDValue1, &ui_font_Kanit50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_LoginPage);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 47);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "ป้อนรหัสคนชั่งน้ำหนักยา");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnEmployeeID2 = lv_obj_create(ui_LoginPage);
    lv_obj_set_width(ui_PnEmployeeID2, 332);
    lv_obj_set_height(ui_PnEmployeeID2, 59);
    lv_obj_set_x(ui_PnEmployeeID2, 0);
    lv_obj_set_y(ui_PnEmployeeID2, 94);
    lv_obj_set_align(ui_PnEmployeeID2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnEmployeeID2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EmployeeIDValue2 = lv_label_create(ui_PnEmployeeID2);
    lv_obj_set_width(ui_EmployeeIDValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmployeeIDValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EmployeeIDValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmployeeIDValue2, "XXXX");
    lv_obj_set_style_text_color(ui_EmployeeIDValue2, lv_color_hex(0xED2677), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EmployeeIDValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EmployeeIDValue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EmployeeIDValue2, &ui_font_Kanit50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Copyright3 = lv_label_create(ui_LoginPage);
    lv_obj_set_width(ui_Copyright3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Copyright3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Copyright3, 0);
    lv_obj_set_y(ui_Copyright3, 223);
    lv_obj_set_align(ui_Copyright3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Copyright3, "CREATE BY NATTAPON PONDONKO");
    lv_obj_set_style_text_color(ui_Copyright3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Copyright3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Copyright3, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Login = lv_btn_create(ui_LoginPage);
    lv_obj_set_width(ui_Login, 153);
    lv_obj_set_height(ui_Login, 57);
    lv_obj_set_x(ui_Login, 90);
    lv_obj_set_y(ui_Login, 165);
    lv_obj_set_align(ui_Login, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Login, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Login);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "เข้าสู่ระบบ");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Details = lv_btn_create(ui_LoginPage);
    lv_obj_set_width(ui_Details, 76);
    lv_obj_set_height(ui_Details, 57);
    lv_obj_set_x(ui_Details, -124);
    lv_obj_set_y(ui_Details, 165);
    lv_obj_set_align(ui_Details, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Details, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Details, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Details, lv_color_hex(0x9A9A9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Details, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Details);
    lv_img_set_src(ui_Image8, &ui_img_house_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 100);

    ui_UserGuide = lv_btn_create(ui_LoginPage);
    lv_obj_set_width(ui_UserGuide, 76);
    lv_obj_set_height(ui_UserGuide, 57);
    lv_obj_set_x(ui_UserGuide, -36);
    lv_obj_set_y(ui_UserGuide, 165);
    lv_obj_set_align(ui_UserGuide, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UserGuide, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UserGuide, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UserGuide, lv_color_hex(0xEEAC44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UserGuide, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_UserGuide);
    lv_img_set_src(ui_Image9, &ui_img_1661776595);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 100);

    ui_PnLoginKeyboard = lv_obj_create(ui_LoginPage);
    lv_obj_set_width(ui_PnLoginKeyboard, 789);
    lv_obj_set_height(ui_PnLoginKeyboard, 420);
    lv_obj_set_x(ui_PnLoginKeyboard, 0);
    lv_obj_set_y(ui_PnLoginKeyboard, 29);
    lv_obj_set_align(ui_PnLoginKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PnLoginKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PnLoginKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PnLoginKeyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PnLoginKeyboard, lv_color_hex(0xAFB4B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnLoginKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginKeyboard = lv_keyboard_create(ui_PnLoginKeyboard);
    lv_keyboard_set_mode(ui_LoginKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_LoginKeyboard, 768);
    lv_obj_set_height(ui_LoginKeyboard, 317);
    lv_obj_set_x(ui_LoginKeyboard, 0);
    lv_obj_set_y(ui_LoginKeyboard, 45);
    lv_obj_set_align(ui_LoginKeyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_LoginKeyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoginKeyboard, lv_color_hex(0xAFB4B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LoginKeyboard, lv_color_hex(0x0DB1A2), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginKeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LoginKeyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoginKeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoginKeyboard, &lv_font_montserrat_40, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_LoginInput = lv_textarea_create(ui_PnLoginKeyboard);
    lv_obj_set_width(ui_LoginInput, 744);
    lv_obj_set_height(ui_LoginInput, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_LoginInput, 0);
    lv_obj_set_y(ui_LoginInput, -156);
    lv_obj_set_align(ui_LoginInput, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_LoginInput, 5);
    lv_textarea_set_placeholder_text(ui_LoginInput, "Employee ID...");
    lv_textarea_set_one_line(ui_LoginInput, true);
    lv_obj_set_style_text_color(ui_LoginInput, lv_color_hex(0x605858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoginInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoginInput, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoginInput, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Details, ui_event_Details, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UserGuide, ui_event_UserGuide, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_LoginKeyboard, ui_LoginInput);

}
