// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Printer

#include "../ui.h"

void ui_QrCodePage_screen_init(void)
{
    ui_QrCodePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_QrCodePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_QrCodePage, lv_color_hex(0x53E1FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QrCodePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_QrCodePage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_QrCodePage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_QrCodePage);
    lv_obj_set_width(ui_Panel8, 340);
    lv_obj_set_height(ui_Panel8, 340);
    lv_obj_set_x(ui_Panel8, 0);
    lv_obj_set_y(ui_Panel8, -56);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QrCodeImg = lv_img_create(ui_Panel8);
    lv_img_set_src(ui_QrCodeImg, &ui_img_1534850174);
    lv_obj_set_width(ui_QrCodeImg, 300);
    lv_obj_set_height(ui_QrCodeImg, 300);
    lv_obj_set_align(ui_QrCodeImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QrCodeImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_QrCodeImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_QrCodeImg, 250);

    ui_Details2 = lv_btn_create(ui_QrCodePage);
    lv_obj_set_width(ui_Details2, 188);
    lv_obj_set_height(ui_Details2, 57);
    lv_obj_set_x(ui_Details2, 0);
    lv_obj_set_y(ui_Details2, 200);
    lv_obj_set_align(ui_Details2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Details2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Details2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Details2, lv_color_hex(0xEA4747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Details2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Details2);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 21);
    lv_obj_set_y(ui_Label36, 0);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "ปิด");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_sukhumvit30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_Details2);
    lv_img_set_src(ui_Image16, &ui_img_close_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image16, -32);
    lv_obj_set_y(ui_Image16, 0);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image16, 180);

    ui_SerialNumber2 = lv_label_create(ui_QrCodePage);
    lv_obj_set_width(ui_SerialNumber2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SerialNumber2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SerialNumber2, 0);
    lv_obj_set_y(ui_SerialNumber2, 145);
    lv_obj_set_align(ui_SerialNumber2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SerialNumber2, "Serial number: ESP32-XXXXXXXX");
    lv_obj_set_style_text_color(ui_SerialNumber2, lv_color_hex(0xF4660A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SerialNumber2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SerialNumber2, &ui_font_sukhumvit25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Details2, ui_event_Details2, LV_EVENT_ALL, NULL);

}
